[project]
name = "nextnet"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.1",
    "mpmath>=1.3.0",
    "numpy>=2.2.3",
    "pyspice>=1.5",
    "python-sat>=1.8.dev14",
]
